default['chef_node']['network']['public'] = '107.184.96.158'
default['chef_node']['network']['bind'] = '10.0.2.15'
default['chef_node']['keys']['priv'] = ''
default['chef_node']['coin'] = 'pivx'
default['chef_node']['tarball'] = 'pivx-2.2.1-x86_64-linux-gnu.tar.gz'
default['chef_node']['package'] = 'pivx-2.2.1'
